const ActionTypes = {
    INIT_APP: 'INIT_APP',
    // Common
    EMPTY: 'EMPTY',
    REDIRECT: 'REDIRECT',
    CLEAR_PATH: 'CLEAR_PATH',
    SET_VALIDSTATUS: 'SET_VALIDSTATUS',
    CANCEL: 'CANCEL',
    // Auth
    SIGNIN: 'SIGNIN',
    SIGNOUT: 'SIGNOUT',
    RESIGNIN: 'RESIGNIN',
    // Setting
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    // Biz
    INIT_LANDING_PAGE: 'INIT_LANDING_PAGE',
    LOAD_LANDING: 'LOAD_LANDING',
    // UI
    BEGIN_LOADING: 'BEGIN_LOADING',
    END_LOADING: 'END_LOADING',
    SHOW_MESSAGE: 'SHOW_MESSAGE',
    HIDE_MESSAGE: 'HIDE_MESSAGE',
    SHOW_LOCKWINDOW: 'SHOW_LOCKWINDOW',
    HIDE_LOCKWINDOW: 'HIDE_LOCKWINDOW'
}
export default ActionTypes;