export default {
    'Navigation.Landing': 'Landing',
    'Navigation.Unknow': 'Unknow',
    'Navigation.About': 'About',
    'Message.UsernameOrPasswordIsNotValid': 'The username or password is not valid!',
    'Message.NetworkException': 'Network Exception: {errorMessage}',
    'Message.SystemException': 'System Exception: {errorMessage}',
    'Message.BusinessException': 'Business Exception: {errorMessage}',
    'Message.404': '404',
    'Message.404Caption': 'Page not found!',
    'Message.UsernameRequired': 'Please input the username!',
    'Message.PasswordRequired': 'Please input the password!',
    'Message.ConfirmPasswordRequired': 'Please confirm the password!',
    'Message.PasswordInconsistent': 'Two passwords that you enter is inconsistent!',
    'Message.EmailInvalid': 'Please input valid email!',
    'Confirm.Delete': 'Are you sure to delete "{name}"? It cannot be recovered!',
    'Label.Brand': 'FewBox',
    'Label.Copyright': 'Design & Deliver App Service by ❤ - ©FewBox 2019',
    'Label.SignIn': 'SignIn',
    'Label.SignInTitle': 'SignIn',
    'Label.SignInDescription': 'Welcome back, please signin your account.',
    'Label.SignUp': 'SignUp',
    'Label.SignOut': 'Sign Out',
    'Label.Username': 'Username',
    'Label.Password': 'Password',
    'Label.ForgotPassword': 'Forgot Password?',
    'Label.RecoverPasswordTitle': 'Recover your password',
    'Label.RecoverPasswordDescription': 'Please enter your email address and we will send you instructions on how to reset your password.',
    'Label.RecoverPassword': 'Recover Password',
    'Label.Email': 'Email',
    'Label.BackToSignIn': 'Back To SignIn',
    'Label.RcoverPassword': 'Recover Password',
    'Label.JWT': 'JWT',
    'Label.Firebase': 'Firebase',
    'Label.Auth0': 'Auth0',
    'Label.RememberMe': 'Remember Me'
}