export default {
    'Navigation.Landing': 'Landing',
    'Navigation.Unknow': 'Unknow',
    'Navigation.About': 'About',
    'Message.UsernameOrPasswordIsNotValid': 'The username or password is not valid!',
    'Message.NetworkException': 'Network Exception: {errorMessage}',
    'Message.SystemException': 'System Exception: {errorMessage}',
    'Message.BusinessException': 'Business Exception: {errorMessage}',
    'Message.404': '404',
    'Message.404Caption': 'Page not found!',
    'Message.UsernameRequired': 'Please input the username!',
    'Message.PasswordRequired': 'Please input the name!',
    'Confirm.Delete': 'Are you sure to delete "{name}"? It cannot be recovered!',
    'Label.Brand': 'FewBox',
    'Label.Copyright': 'Design & Deliver App Service by ❤ - ©FewBox 2019',
    'Label.SignIn': 'SignIn',
    'Label.SignUp': 'SignUp',
    'Label.SignOut': 'Sign Out',
    'Label.Username': 'Username',
    'Label.Password': 'Password',
    'Label.ForgotPassword': 'Forgot Password?',
    'Label.JWT': 'JWT',
    'Label.Firebase': 'Firebase',
    'Label.Auth0': 'Auth0',
    'Label.RememberMe': 'Remember Me'
}